version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build
      - test
      - lint
      # - analyze
jobs:
  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: npm install
      - save_cache:
          key: "npm packages"
          paths:
            - /src/node_modules
      - run: npm run lint

  test:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - "npm packages"
      - run: npm install
      - run: npm run test
  lint:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - "npm packages"
      - run: npm install
      - run: npm run lint

  analyze:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - "npm packages"
      - run: npm audit
